/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "outline-variant": "#c7c4d8",
                "outline": "#777587",
                "surface-tint": "#4d44e3",
                "on-surface": "#1b1b24",
                "on-tertiary-fixed-variant": "#7b2f00",
                "on-tertiary-fixed": "#351000",
                "on-error": "#ffffff",
                "on-secondary-container": "#54647a",
                "surface-container-high": "#eae6f4",
                "inverse-surface": "#302f39",
                "on-surface-variant": "#464555",
                "on-secondary": "#ffffff",
                "surface": "#fcf8ff",
                "on-tertiary": "#ffffff",
                "primary-container": "#4f46e5",
                "tertiary": "#7e3000",
                "primary": "#3525cd",
                "on-error-container": "#93000a",
                "error": "#ba1a1a",
                "primary-fixed-dim": "#c3c0ff",
                "on-primary-fixed": "#0f0069",
                "surface-container-low": "#f5f2ff",
                "secondary-fixed": "#d3e4fe",
                "inverse-primary": "#c3c0ff",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#3323cc",
                "secondary-container": "#d0e1fb",
                "surface-dim": "#dcd8e5",
                "on-primary": "#ffffff",
                "background": "#fcf8ff",
                "surface-container-lowest": "#ffffff",
                "surface-variant": "#e4e1ee",
                "inverse-on-surface": "#f3effc",
                "on-primary-container": "#dad7ff",
                "surface-container-highest": "#e4e1ee",
                "secondary-fixed-dim": "#b7c8e1",
                "on-secondary-fixed-variant": "#38485d",
                "surface-bright": "#fcf8ff",
                "tertiary-fixed-dim": "#ffb695",
                "tertiary-container": "#a44100",
                "primary-fixed": "#e2dfff",
                "on-tertiary-container": "#ffd2be",
                "on-secondary-fixed": "#0b1c30",
                "secondary": "#505f76",
                "surface-container": "#f0ecf9",
                "on-background": "#1b1b24",
                "tertiary-fixed": "#ffdbcc"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "sm": "8px",
                "xs": "4px",
                "base": "8px",
                "lg": "24px",
                "2xl": "48px",
                "gutter": "24px",
                "md": "16px",
                "xl": "32px",
                "margin": "32px"
            },
            fontFamily: {
                "h1": ["Inter"],
                "h2": ["Inter"],
                "h3": ["Inter"],
                "label-md": ["Inter"],
                "label-sm": ["Inter"],
                "body-lg": ["Inter"],
                "body-md": ["Inter"],
                "body-sm": ["Inter"]
            },
            fontSize: {
                "h1": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "h2": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "h3": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};
